site_name: QMETA-MD-DOCSTIE
site_description: A Template Repo to build help documents
pages:
  - 介绍: README.md
  - mkdocs:
    - "mkdocs-tip": 'mkdocs/Index.md'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: pink
    accent: pink
  logo:  'assets/logo.png'
  favicon: 'assets/favicon.png'